#!/bin/bash

# stop on any error
set -euo pipefail

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. ${root_directory}/configurations/gke.sh

# create cluster
${root_directory}/clis/gcloud container clusters get-credentials ${gke_cluster_name}
