#!/bin/bash

usage(){
    echo "${0} requires container_name"
    echo "example: ${0} foo"
}

# usage
if [[ ${1} == "" ]]
then usage; exit 1
fi

# stop on any error
set -euo pipefail

# set parameters
container_name=${1}

# kill
container_running=$(docker ps -q -f name=${container_name})
if [[ "${container_running}" != "" ]]
then docker kill ${container_running} > /dev/null
fi

# remove
container_existing=$(docker ps -q -a -f name=${container_name})
if [[ "${container_existing}" != "" ]]
then docker rm ${container_existing} > /dev/null
fi
