#!/bin/bash

# stop on any error
set -euo pipefail

# create cluster
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
${root_directory}/containers/googleclis/googleclis_asdaemon.sh \
    kubernetes_proxy \
    kubectl proxy --address='0.0.0.0'
